export function square(scale?: number): FOLD;
export function rectangle(width?: number, height?: number): FOLD;
export function polygon(sides?: number, circumradius?: number): FOLD;
export function blintz(): FOLD;
export function kite(): FOLD;
export function fish(): FOLD;
export function bird(): FOLD;
export function frog(): FOLD;
export function windmill(): FOLD;
export function squareFish(): FOLD;
