export function epsilonEqual(a: number, b: number, epsilon?: number): boolean;
export function epsilonCompare(a: number, b: number, epsilon?: number): number;
export function epsilonEqualVectors(a: number[], b: number[], epsilon?: number): boolean;
export function include(n: number, epsilon?: number): boolean;
export function exclude(n: number, epsilon?: number): boolean;
export function includeL(_: number, __?: number): boolean;
export function excludeL(_: number, __?: number): boolean;
export function includeR(n: number, epsilon?: number): boolean;
export function excludeR(n: number, epsilon?: number): boolean;
export function includeS(n: number, e?: number): boolean;
export function excludeS(n: number, e?: number): boolean;
