export function normalAxiom1InPolygon(polygon: [number, number][], point1: [number, number], point2: [number, number]): UniqueLine[];
export function axiom1InPolygon(polygon: [number, number][], point1: [number, number], point2: [number, number]): VecLine2[];
export function normalAxiom2InPolygon(polygon: [number, number][], point1: [number, number], point2: [number, number]): UniqueLine[];
export function axiom2InPolygon(polygon: [number, number][], point1: [number, number], point2: [number, number]): VecLine2[];
export function normalAxiom3InPolygon(polygon: [number, number][], line1: UniqueLine, line2: UniqueLine): UniqueLine[];
export function axiom3InPolygon(polygon: [number, number][], line1: VecLine2, line2: VecLine2): VecLine2[];
export function normalAxiom4InPolygon(polygon: [number, number][], line: UniqueLine, point: [number, number]): UniqueLine[];
export function axiom4InPolygon(polygon: [number, number][], line: VecLine2, point: [number, number]): VecLine2[];
export function normalAxiom5InPolygon(polygon: [number, number][], line: UniqueLine, point1: [number, number], point2: [number, number]): UniqueLine[];
export function axiom5InPolygon(polygon: [number, number][], line: VecLine2, point1: [number, number], point2: [number, number]): VecLine2[];
export function normalAxiom6InPolygon(polygon: [number, number][], line1: UniqueLine, line2: UniqueLine, point1: [number, number], point2: [number, number]): UniqueLine[];
export function axiom6InPolygon(polygon: [number, number][], line1: VecLine2, line2: VecLine2, point1: [number, number], point2: [number, number]): VecLine2[];
export function normalAxiom7InPolygon(polygon: [number, number][], line1: UniqueLine, line2: UniqueLine, point: [number, number]): UniqueLine[];
export function axiom7InPolygon(polygon: [number, number][], line1: VecLine2, line2: VecLine2, point: [number, number]): VecLine2[];
