declare const _default: {
    validateAxiom1: (boundary: number[][], solutions: VecLine[], point1: number[], point2: number[]) => boolean[];
    validateAxiom2: (boundary: number[][], solutions: VecLine[], point1: number[], point2: number[]) => boolean[];
    validateAxiom3: (boundary: number[][], solutions: VecLine[], line1: VecLine, line2: VecLine) => boolean[];
    validateAxiom4: (boundary: number[][], solutions: VecLine[], line: VecLine, point: number[]) => boolean[];
    validateAxiom5: (boundary: number[][], solutions: VecLine[], line: VecLine, point1: number[], point2: number[]) => boolean[];
    validateAxiom6: (boundary: number[][], solutions: VecLine[], line1: VecLine, line2: VecLine, point1: number[], point2: number[]) => boolean[];
    validateAxiom7: (boundary: number[][], solutions: VecLine[], line1: VecLine, line2: VecLine, point: number[]) => boolean[];
    validateAxiom: (number: number, boundary: number[][], solutions: VecLine[], ...args: any[]) => boolean | boolean[];
    axiomWithBoundary: (number: number, boundary: number[][], ...args: any[][][]) => VecLine[];
    normalAxiomWithBoundary: (number: number, boundary: number[][], ...args: any[][][]) => UniqueLine[];
    normalAxiom1: (point1: [number, number], point2: [number, number]) => [UniqueLine];
    axiom1: (point1: [number, number], point2: [number, number]) => [VecLine2];
    normalAxiom2: (point1: [number, number], point2: [number, number]) => [UniqueLine];
    axiom2: (point1: [number, number], point2: [number, number]) => [VecLine2];
    normalAxiom3: (line1: UniqueLine, line2: UniqueLine) => [UniqueLine?, UniqueLine?];
    axiom3: (line1: VecLine2, line2: VecLine2) => [VecLine2?, VecLine2?];
    normalAxiom4: (line: UniqueLine, point: [number, number]) => [UniqueLine];
    axiom4: ({ vector }: VecLine2, point: [number, number]) => [VecLine2];
    normalAxiom5: (line: UniqueLine, point1: [number, number], point2: [number, number]) => [UniqueLine?, UniqueLine?];
    axiom5: (line: VecLine2, point1: [number, number], point2: [number, number]) => VecLine2[];
    normalAxiom6: (line1: UniqueLine, line2: UniqueLine, point1: [number, number], point2: [number, number]) => UniqueLine[];
    axiom6: (line1: VecLine2, line2: VecLine2, point1: [number, number], point2: [number, number]) => VecLine2[];
    normalAxiom7: (line1: UniqueLine, line2: UniqueLine, point: [number, number]) => [UniqueLine?];
    axiom7: (line1: VecLine2, line2: VecLine2, point: [number, number]) => [VecLine2?];
    axiom: (number: number, ...args: any[]) => VecLine2[];
    normalAxiom: (number: number, ...args: any[]) => UniqueLine[];
};
export default _default;
