import classes_nodes from './classes_nodes.js';
/**
 * SVG (c) Kraft
 */
export const nodeNames: string[];
export namespace placeholder {
    let svg: any;
    let defs: any;
    let desc: any;
    let filter: any;
    let metadata: any;
    let style: any;
    let script: any;
    let title: any;
    let view: any;
    let cdata: any;
    let g: any;
    let circle: any;
    let ellipse: any;
    let line: any;
    let path: any;
    let polygon: any;
    let polyline: any;
    let rect: any;
    let arc: any;
    let arrow: any;
    let curve: any;
    let parabola: any;
    let roundRect: any;
    let wedge: any;
    let origami: any;
    let text: any;
    let marker: any;
    let symbol: any;
    let clipPath: any;
    let mask: any;
    let linearGradient: any;
    let radialGradient: any;
    let pattern: any;
    let textPath: any;
    let tspan: any;
    let stop: any;
    let feBlend: any;
    let feColorMatrix: any;
    let feComponentTransfer: any;
    let feComposite: any;
    let feConvolveMatrix: any;
    let feDiffuseLighting: any;
    let feDisplacementMap: any;
    let feDistantLight: any;
    let feDropShadow: any;
    let feFlood: any;
    let feFuncA: any;
    let feFuncB: any;
    let feFuncG: any;
    let feFuncR: any;
    let feGaussianBlur: any;
    let feImage: any;
    let feMerge: any;
    let feMergeNode: any;
    let feMorphology: any;
    let feOffset: any;
    let fePointLight: any;
    let feSpecularLighting: any;
    let feSpotLight: any;
    let feTile: any;
    let feTurbulence: any;
}
export { classes_nodes as default };
